### ISSUE TITLE
ExtractMatrix: incorrect SAM parsing

### ISSUE THREAD

**Issue by maciejmotyka** [WuLoli/GAEseq#2]
The `ExtractMatrix` script seems to be unable to parse SAM files properly. Neither any of my own files nor the example file.

My files
-----
Let's start with one of my samples. It was mapped to reference with Geneious Mapper. There are 
26402 mapped reads, of which 26374 are paired and 28 are unpaired. There are no unmapped reads.
```
$ samtools flagstat 03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam 

26402 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
26402 + 0 mapped (100.00% : N/A)
26374 + 0 paired in sequencing
13187 + 0 read1
13187 + 0 read2
26374 + 0 properly paired (100.00% : N/A)
26374 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
`ExtractMatrix` reports that 99% of the reads are singletons and refuses to use them for QSR, thus utilizing only 284 of 26402 reads. It also finds 1 unmapped read.
```
$ ../ExtractMatrix config

mapped_counter:284 unmapped_counter:1
num_lowQSseq:2 seq_count:284
filtered_counter1:0 filtered_counter2:0
 filtered_cond2:284
pair_counter:285 singleton_counter:26117 total_counter:26402

After parsing 26402 reads in file /home/lejno/Desktop/WDV/2020/mapped-to-circular-consensus/03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam, there are 284 paired_end reads(mean lengths 157.93) covering regions 1-2751.
CPU time for SAM parsing: 0.122541

After calling SNVs from 2751 bases in regions between 1 and 2751, 2730 SNVs are detected.
After correcting error, 284 fragments are used for quasi-species reconstruction.
reduced number of fragment:0
CPU time for SNV calling: 0.017606
```

Example file
-----
Now, let's look at the `K2_Cov5_Sample1.sam` that comes with the repo. It has 200 paired reads.
```
samtools flagstat K2_Cov5_Sample1.sam
200 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
200 + 0 mapped (100.00% : N/A)
200 + 0 paired in sequencing
100 + 0 read1
100 + 0 read2
200 + 0 properly paired (100.00% : N/A)
200 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
`ExtractMatrix` recognizes 100 of 200 reads as singletons. In effect, only half of the reads are used for quasispecies reconstruction.
```
mapped_counter:100 unmapped_counter:0
num_lowQSseq:0 seq_count:100
filtered_counter1:0 filtered_counter2:0
 filtered_cond2:100
pair_counter:100 singleton_counter:100 total_counter:200

After parsing 200 reads in file K2_Cov5_Sample1.sam, there are 100 paired_end reads(mean lengths 549.35) covering regions 1-5000.
CPU time for SAM parsing: 0.0109

After calling SNVs from 5000 bases in regions between 1 and 5000, 467 SNVs are detected.
After correcting error, 100 fragments are used for quasi-species reconstruction.
reduced number of fragment:0
```

**Comment by maciejmotyka** [comment]
* For the example file I used the example config provided with repo.
* For my own file I used this config:
```
filename of reference sequence (FASTA) : /home/lejno/Desktop/WDV/2020/WDV-consensus-refseq.fasta
filname of the aligned reads (sam format) : /home/lejno/Desktop/WDV/2020/mapped-to-circular-consensus/03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam
SNP_thres (0.5 / ploidy) : 0
reconstruction_start : 1
reconstruction_stop : 2751
min_mapping_qual : 40
min_read_length : 10
max_insert_length : 2751
characteristic zone name : 03_WDV_RefSeq
Initial population size : 2
Graph Convolutional layer number (must be even) : 2
Number of experiments : 200
dropout probability of read nodes to SNP nodes layer : 0
dropout probability of SNP nodes to read nodes layer : 0
dropout probability of dense layer : 0
Which GPU to use (set to -1 if only use CPU; otherwise set to 0, 1, 2 or 3 ...if multiple GPUs are available; check instructions for details) : -1
```
* This the head of my .sam file:
```
$ head -n 6 03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam

@HD	VN:1.0	SO:unsorted
@SQ	SN:WDV-consensus-RefSeq	LN:2751
@RG	ID:Unpaired_reads_assembled_against_WDV-consensus-RefSeq	SM:03_S7_R_clean assembled to WDV-consensus-RefSeq
@RG	ID:Paired_Group_1_assembled_against_WDV-consensus-RefSeq	PI:600	SM:03_S7_R_clean assembled to WDV-consensus-RefSeq
M01939:25:000000000-AC3BN:1:2106:22733:7834 2:N:0:7%26M01939:25:000000000-AC3BN:1:2106:22733:7834 1:N:0:7	83	WDV-consensus-RefSeq	1	254	19M1P92M1I4M	=	2309	2577	ACCCCGCGTGGTGGCCCCCGACGCGCACTCGGCTTTTCGTGAGTGCGCGGAGGCTTTTGGACCACATCTTTTCTGAGAACTTTCGTGGAAGATGGTGATTTATCACACTTTGTGAC	F:F@FEBF<FF=@F@44=CGGGEGF?B8B:GGCGF7FEF<GGGGGEEFGFAFEC<E9GGGFFAFGDCC,EF<CEGGGGGGGGFFGGGGGGGFCGGGGGGGGGGGGGFGGGFCCCC9	RG:Z:Paired_Group_1_assembled_against_WDV-consensus-RefSeq
M01939:25:000000000-AC3BN:1:1116:22492:15693 2:N:0:7%26M01939:25:000000000-AC3BN:1:1116:22492:15693 1:N:0:799	WDV-consensus-RefSeq	1	254	19M1P92M1I54M1P5M	=	43	309	ACCCCGCGTGGTGGCCCCCGACGCGCACTCGGCTTTTCGTGAGTGCGCGGAGGCTTTTGGACCACATCTTTTCTGAGAACTTTCGTGGAAGATGGTGATTTATCACACTTTGTGACGCGGAAATGTGTGCCATGCCTTAGCTTATAAGGAAGTGCGTGGTAGCCCATCTCG	CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG?FFEGGGGGGGGGGGFFCFFGGGGGGGGFGCFGGG:DGGGGGGGFGFGFAFEGF9FCG7C7@+=9FGGFGGFFGGGFFFGGGGGFGCAFGFFGFGGGGGGCFG7C>7FFGF	RG:Z:Paired_Group_1_assembled_against_WDV-consensus-RefSeq
```
I can email you the whole .sam file if you want.

**Comment by maciejmotyka** [comment]
It looks like `TenSQR` uses the same `ExtractMatrix` script. This may be the reason behind [TenSQR issue #7](https://github.com/SoYeonA/TenSQR/issues/7). I didn't catch it then because I used `TenSQR` inside a Nextflow pipeline which didn't log the `ExtractMatrix` output to console.

Does `aBayesQR` use the same exact code to parse sam files?

**Comment by WuLoli** [comment]
The code used to parse sam files is adapted from PredictHaplo(http://bmda.cs.unibas.ch/software.html)

For the example file, there are only 200 single reads (As shown with samtools flagstat K2_Cov5_Sample1.sam, there are 100 + 0 read1 and 100 + 0 read2) in the SAM file (You could open the SAM file as a text file and count). Below are the first 4 single reads.


reference_l_5000_iter_1-100	83	reference_l_5000_iter_1	1846	60	250M	=	1545	-551	CACTCGACGCGAGCAGGCTATCAGAGAGACTGCCTATAAAGCGGATCTCTGAGGGAGTGTTCTACATCAGCTGTTGAAAATTCGGAGCACATGGGGTCTTATTATCAGCGGTCGGGCTGGTATTTGCTAGCGCGTCCCAACTTCGATCGTAGTTCCTCCGTTACTCAGTCTTGCCGCAGCCAGGTCTTGGAGGTGATACCGAGCGATGTTAAGGCAGTCAGAACTTCACGTCGCACCAGCGCCGAACCTA	GGCG?G*EGG*F0?GGE8E:GGE:CC;E?GG?@EHGFHHHD=:GC<GEEE:FEGGGG6CGGGFGG?GGE+EG9FGDEGGECGCGGEFFG;FFAG6GGGFG<AFGBECFGFEEEDFHEGGG?FEDHHHDHHFHGHIHFEEHEHIIHHHHF/IIHHIEHIHIIIGIIHGDHICI5HHIH-HHDIGHFHHE=7H-HHHHHFHIIIE5HIFIICFIIIHFIAHIHIHFFHIIGGGGFGDB?DDD9EBB?5A???	NM:i:16	MD:Z:10T2G2T0G9A33T14T0T18C1G0A8T58C60G11T4T4	MC:Z:236M14S	AS:i:172	XS:i:0
reference_l_5000_iter_1-100	163	reference_l_5000_iter_1	1545	60	236M14S	=	1846	551	GGCAACCTGTATAAGATTCTTGCGAATGCTTTGACGAGCGTGCGTATTCAGTCTCAGTTGCGGTGTGCAGTATGGTTAGGAACAGTGATTGCCTTTTAGCTAGGTTAGAGTTCGACGTCAGACAGGTAATTCCATGTCCCGTCCACGTGAATTAGCCTTTACCTGATTTCCAGTAATCCCGTCATCAGTTAGCTAACCGCAGGCGCTTGTTAGTTCGAGACAGCGGGCGGTTGGTGAACATAACGTGAAT	??A??BBBDD@BDDDDF?FGFF8/HHHHFIFI-FBI@EFFIHHH7HC9IH9IFHAI5F-G=FIGIFFDIE5IHHCAFIHHIIFDIIHHFI7HHGIG@ECI,HFIF;HCCDGHEHHHGEFFFG@GHF;FF<4A=EG>FAEG(AC@EFGFGGGDG,*?(GGGFEEG0GEG?C;GEGFGF:;EECGEE##'G0?EDGAG*.'?E:?G(EH':HAG/4C*:GCECC?EGGDG8CE?E:E6(E:#EC:6C*:?GA	NM:i:22	MD:Z:35A18G1C1C12C0A3C0T3C3A2A43G7T9G9G26A8T6G8C0G4A3A13	MC:Z:250M	AS:i:126	XS:i:0
reference_l_5000_iter_1-98	99	reference_l_5000_iter_1	1265	60	250M	=	1634	549	AAAGCCGCGGAGCCTAACCAAGCGGCTTATCTAGAAGGGTCGCATTACGTGACGGGTTGCTGCGAATGGTGCTCATACGCTGTTGTATCGCGGTTCTGAACCTCATTGAAAATCCATGTAACCTCAGTAGCACATTTATCACCCCAACTATATGGTCCCTAACTTATGGGAGCTGAAAATATCCTATACCGTCGTCGAAACAGAGATGCCTACTTTATTGGAACCCTGATAGTAGCAGGGAGGACGTTTT	??A???BBD<DDDDDDFFGGC/H/H.IIIBIHIHHHCHIHHHIIHIFIHIHHIHHHHDF8HEIGHHIIIHIIHIIHGIIHH#HHDHHFHHHHHFIIDHHIFFEHCHCHHFFFGCGGHHGGDH=HAEDHFF,FGGGDGEDGEGFGAEGG0FGEGG??EGDECAEEGCGGCAG?GB+:EGEGGFGGFEHCEG:EGGED*FGGAG*G*EEECGEH:HC0EGGGGGFEGEE)EAC:0CE0EEGEEG(<8CGE0G	NM:i:22	MD:Z:1C15T8A7C0T5A11A18C4G3T4C1G10T14A3C19G35T1C11T36A10T1A11	MC:Z:70S180M	AS:i:143	XS:i:0
reference_l_5000_iter_1-98	147	reference_l_5000_iter_1	1634	60	70S180M	=	1265	-549	TTGCGACTGCTTTGACGAGCGTACGTATTCAGTCTCATTTGCAGTGAGCAGTATGGTTAGGAACAGTGATTGCCTTTTAGCTAGGTTAGAGTTCGACGTCAGACAGGTAATTCCATGTCCCTTCCACGTGAATTAGCCTTTACCTGATTTCCAGTAATCCCGTCATCAGTTAGCTAATCGCACGCGCTTGTTAGTTCGAGACAGCGGGCGGTTGGTGGACCTAACGTGAATTCCTGCTGAAAGCGGGGTC	G:?GCE(88CC6F:G/:GG*CA(6G?EDEEG:GCEG@FA(F:(:GE(FEG?GGG:'*FCE*C;CE/G>GGEAE4C<E0GFE@GEG(EE;E(G3F<EGE?FG*GE?AG*GEEEEGEEEEGBE5GGHHFCHG=HDF*+E6H;GIGDEEIFHHFFHDHHHGCD=HIEFE-(HIFIAHGIIHHGDI+IHHIHFIE8.>HFHIH>IIFH-DFHIHIHIIEIIIHEFIHEHIFIFGGGC8@DD5?EBDBA??A???	NM:i:15	MD:Z:43G17G9G26A13G1G8C0G4A3A19G6A1T3T1A11	MC:Z:250M	AS:i:105	XS:i:0


The name of the first 2 reads is reference_l_5000_iter_1-100 and the name of the 3rd and 4th reads is reference_l_5000_iter_1-98, meaning that the first 2 reads are paired and the 3rd and 4th reads are paired. Therefore, the whole 200 reads form 100 paired-end reads and all these 100 paired-end reads are used to construct the SNP matrix. 

I guess the reason why the code only finds 284 paired-end reads from your SAM file is that the length of the reference genome is far more than 2751. Only 284 paired-end reads are covering this region. If this is not the case, another reason could be that only 284 pairs share the same name in the SAM file. If these cannot solve the problem and if you don't mind, please send the fastq (reads) and fasta (reference) files to ziqike@utexas.edu and I could have a look. 

Hope this helps!

**Comment by WuLoli** [comment]
By the way, we have done all the alignments via BWA MEM algorithm and there is no problem to use ExtractMatrix with the resulted SAM file. You could try to map the reads (fastq file) to the reference (fasta file) using BWA MEM and then run ExtractMatrix.

**Comment by maciejmotyka** [comment]
> Therefore, the whole 200 reads form 100 paired-end reads and all these 100 paired-end reads are used to construct the SNP matrix.

I have examined the files produced by `ExtractMatrix` from `K2_Cov5_Sample1.sam` and indeed it uses all 200 reads. Sorry for the false alarm, I got confused by the `singleton_counter:100` and `100 fragments are used`.

> I guess the reason why the code only finds 284 paired-end reads from your SAM file is that the length of the reference genome is far more than 2751. Only 284 paired-end reads are covering this region. 

I used Geneious because it can properly map the reads spanning the origin of circular genomes. So, yes, some reads will extend beyond the 2751, but roughly 90% of the read pairs are mapped within the 1-2751 range. I extended the range to `reconstruction_stop : 3500` to encompass 100% of reads, but it didn't help. Neither did mapping to linear version of the genome.

> another reason could be that only 284 pairs share the same name in the SAM file.

I counted the duplicated QNAMEs and it matches the values returned by `samtools flagstat`
```
$ samtools view 03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam | cut -f 1 | sort | uniq -d | wc -l
13187

$ samtools flagstat 03_S7_R_clean_assembled_to_WDV-consensus-refseq.sam
26374 + 0 paired in sequencing
13187 + 0 read1
13187 + 0 read2
26374 + 0 properly paired (100.00% : N/A)
26374 + 0 with itself and mate mapped
```

I'll look at the code of `ExtractMatrix` and try to figure out what's the problem. If I'm not able I'll send you the data.

**Comment by maciejmotyka** [comment]
FYI: it seems that Geneious Mapper outputs a SAM file that is incompatible with `Extract Matrix`. The file seems to be a valid SAM, because all of the common SAM visualization/manipulation programs had no trouble displaying/reporting all of the reads. I decided to use BWA MEM instead of trying to resolve this issue.
